Вычисления с помощью Nampy
Задание 1

In [1]:
import numpy as np
a=np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [2]:
mean_a=a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2

In [3]:
a_centered=a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [4]:
a1=a_centered[:,0]
a2=a_centered[:,1]
a_centered_sp=np.dot(a1,a2)
n_1=a_centered.shape[0]-1
b=a_centered_sp/n_1
b

2.0

Задание 4

In [5]:
a_cov=np.cov(a.transpose())
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

Работа с данными в Pandas
Задание 1

In [6]:
import pandas as pd
authors=pd.DataFrame({'author_id':[1,2,3], 'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id','author_name'])
authors

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [7]:
books=pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],'price':[450, 300, 350, 500, 450, 370, 290]},columns=['author_id','book_title','price'])
books

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [8]:
authors_price=pd.merge(authors, books, on='author_id', how='inner')
authors_price

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [9]:
top5=authors_price.nlargest(5, 'price')
top5

   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

In [10]:
max=authors_price.groupby('author_name')['price'].max()
min=authors_price.groupby('author_name')['price'].min()
mean=authors_price.groupby('author_name')['price'].mean()
authors_stat=pd.merge(min, max, on='author_name', how='inner')
authors_stat=pd.merge(authors_stat, mean, on='author_name', how='inner')
authors_stat=authors_stat.rename(columns={'price_x':'min_price', 'price_y':'max_price', 'price':'mean_price'})
authors_stat

             min_price  max_price  mean_price
author_name
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

Задание 5

In [11]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

   author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [13]:
book_info=pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [14]:
book_info.to_pickle('book_info.pkl')
book_info2=pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name
Островский      660        0
Тургенев        650      450
Чехов             0      950